# Generated by Django 5.2.16 on 2026-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('year', models.CharField(help_text='e.g. 2021 - 2025', max_length=100)),
                ('grade_or_skills', models.CharField(blank=True, help_text='e.g. CGPA: 9.2 or Core Python', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=300)),
                ('responsibilities', models.TextField(help_text='Newline-separated list of achievements/responsibilities')),
                ('start_date', models.CharField(help_text='e.g. Jan 2024', max_length=100)),
                ('end_date', models.CharField(blank=True, help_text='e.g. Present or Dec 2024', max_length=100, null=True)),
                ('current', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('technologies', models.TextField(help_text='Comma-separated list of technologies')),
                ('features', models.TextField(help_text='Newline-separated list of features')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback external image URL', max_length=500, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI/Data Science', 'AI & Data Science'), ('Tools', 'Tools & Others')], max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Skill proficiency from 0 to 100')),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Code, Database, Globe)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('icon_name', models.CharField(help_text='Lucide icon name (e.g. Github, Linkedin, Mail)', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
