# Generated by Django 5.2.16 on 2026-08-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='local_path',
            field=models.CharField(blank=True, help_text='Local directory path of the project manage.py', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='local_port',
            field=models.IntegerField(blank=True, help_text='Port number to launch the project server locally', null=True),
        ),
    ]
